About RemoteApplications
========================

**Note:** RemoteApplications is replaced by the new `remoteswinglibrary`__ project,
as in most cases RemoteApplications was simply used with SwingLibrary.


RemoteApplications is a `Robot Framework`_ (RF) test library that is used for
launching Java applications on a separate JVM and taking other libraries into
use on them. This is useful when application does something that
cannot be tested with RF when running on the same JVM. Such cases are when
`System.exit` is called by the tested application, when multiple applications
running on separate JVMs need to be tested in parallel, or when application is
started using Java Web Start.

See `Wiki`__ for usage instructions and tips.

This projects started as part of `robotframework-javatools`__ project but is
nowadays a separate project.

Downloads
=========

The project jar can be downloaded `google-code`__

Developing RemoteApplications
=============================

Starting from version 2.0 the project is built using only maven.

Run mvn package to compile the project and mvn verify to run robot tests.

.. _Robot Framework: http://robotframework.org
__ https://github.com/robotframework/remoteswinglibrary
__ https://github.com/robotframework/RemoteApplications/wiki
__ http://code.google.com/p/robotframework-javatools
__ http://code.google.com/p/robotframework-javatools/downloads/list
